[package]
name = "rsa-securid"
version = "0.1.0"
authors = ["Alpha Chen <alpha@kejadlen.dev>"]
edition = "2018"

[dependencies]
bytes = "0.5"
clap = "2.33"
chrono = "0.4"
openssl = "0.10"
regex = "1"
